[package]
name = "tileworld_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "0.8.7"
priority-queue = "1.3.2"
log = "0.4.19"
